# Generated by Django 3.0.5 on 2020-04-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_catchphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='catchphrase',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
